### ISSUE TITLE
How do I change timeout?

### ISSUE THREAD

**Issue by yoavlt** [dkataskin/erlazure#14]

**Comment by dkataskin** [comment]
Timeout of an http request or azure service request timeout?

**Comment by yoavlt** [comment]
Thank you for your reply.
I want to use this module for big file upload from Elixir.

The error message is as below.
(EXIT from #PID<0.214.0>) exited in: :gen_server.call(#PID<0.216.0>, {:put_blob, 'test', 'file', :block_blob, <<0, 0, 0, 20, 102, 116, 121, 112, 113, 116, 32, 32, 0, 0, 0, 0, 113, 116, 32, 32, 0, 0, 0, 8, 119, 105, 100, 101, 1, 11, 17, 204, 109, 100, 97, 116, 32, 102, 32, 1, 152, 128, 14, 33, 76, ...>>, []})
         ** (EXIT) time out

I don't know how to change timeout, but it seems to upload successfully :sob:

**Comment by dkataskin** [comment]
Thank you for reporting this issue, I will look into and add http timeout and azure service request timeout options, can you share "big" file sample you are trying to upload?

**Comment by yoavlt** [comment]
Thank you very much! :bow: :bow: 
This is a sample file!
https://app.box.com/s/j05jxi6vqaouclwp3wr8c9i3fqem831w

**Comment by yoavlt** [comment]
Awesome!!! :clap: :clap:
