### ISSUE TITLE
OPT24 crypto deprecations

### ISSUE THREAD

**Issue by mize85** [dkataskin/erlazure#32]
Hiho @dkataskin,

OTP24 removed some crypto functions which were deprecated in OTP23
http://erlang.org/doc/general_info/deprecations.html

I do not write erlang usually but e.g. https://github.com/epgsql/epgsql/pull/239/files seem to fix it in a backwards compatible way.

I tried to create a PR but the formatting is completely messed up 🤦 
https://github.com/dkataskin/erlazure/pull/31

Are there plans to support OTP24?

Best regards.

**Comment by ariel-anieli** [comment]
Fixed in https://github.com/dkataskin/erlazure/pull/33
